# Generated by Django 3.0.3 on 2020-04-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=264, unique=True)),
                ('Email_Address', models.CharField(max_length=264, unique=True)),
            ],
        ),
    ]
