# Generated by Django 3.0.3 on 2020-04-16 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
