# Generated by Django 3.0.3 on 2020-04-23 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Email_Address',
            field=models.EmailField(max_length=264),
        ),
        migrations.AlterField(
            model_name='user',
            name='First_Name',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='user',
            name='Last_Name',
            field=models.CharField(max_length=264),
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.URLField(blank=True)),
                ('picture', models.ImageField(upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='first_app.User')),
            ],
        ),
    ]
