# Generated by Django 3.0.3 on 2020-04-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_auto_20200426_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=264)),
                ('Last_Name', models.CharField(max_length=264)),
                ('Email_Address', models.EmailField(max_length=264)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='portfolio_site',
            field=models.URLField(blank=True, max_length=264),
        ),
    ]
